### ISSUE TITLE
Items to accomplish

### ISSUE THREAD

**Issue by edysegura** [univas/list-of-names#1]
- [x] [Add HTML5 form validation](https://github.com/univas/list-of-names/commit/874c616e0423211463a07354e17f11d28d2afdd1)
- [x] Refactor to use modules
  -  [Added ListService.js](https://github.com/univas/list-of-names/commit/a1039b484097816fbfdfbf1376f33bbbd869e008)
  - [Added ListController.js](https://github.com/univas/list-of-names/commit/1bbdb18f416a9230363cfc68840f0d566dbc762f)
  - [HTML intregation to display added name](https://github.com/univas/list-of-names/commit/059c00d63587b9afca818c8329fc3e7be8968c1e)
  - [Implement HTMLService.js](https://github.com/univas/list-of-names/commit/3d0313d41635baf902615b25effccf7d42076adc)
- [x] [HTML5 localStorage](https://github.com/univas/list-of-names/commit/b1bcb2857123d0c1ed002f683df2decfb083daf5)
- [x] [Apply CSS to improve layout](https://github.com/univas/list-of-names/commit/448629d6668d8adb801fe92ccd4d0eb75b8c2a1d)
- [x] [Create GitHub pages](http://univas.github.io/list-of-names/)

**Comment by AnniePresciliana** [comment]
Criar o HTML Service

**Comment by simaofaustino123** [comment]
👍
